
trigger: none
  # branches:
  #   include:
  #     - main

pool:
  vmImage: 'windows-latest'

steps:

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact'
    inputs:
      artifactName: 'TestAutomation'
      path: '$(System.DefaultWorkingDirectory)'

  # - task: DotNetCoreCLI@2
  #   displayName: 'Run unit tests'
  #   inputs:
  #     command: test
  #     projects: '**/UnitTests.csproj'
  #     arguments: '--filter FullyQualifiedName~TestSingle'

  # - task: VSTest@2
  #   displayName: 'Test run for Test plans'
  #   inputs:
  #     testSelector: testRun
  #     vsTestVersion: 15.0
  #     runInParallel: false
  #     runTestsInIsolation: false
  #     codeCoverageEnabled: false
  #   continueOnError: true

  - task: VSTest@2
    displayName: 'Run test plan 2580'
    inputs:
      testRunTitle: 'Test run title'
      testSelector: 'testPlan'
      testPlan: '2580'
      testSuite: '2581'
      testConfiguration: '124'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      runSettingsFile: '/path/to/runsettings/or/testsettings/file'
      overrideTestrunParameters: '-key1 value1 -key2 value2'
      # runInParallel: false
      # runTestsInIsolation: false
      # codeCoverageEnabled: false
      # failOnMinTestsNotRun: false
      # resultsFolder: $(Agent.TempDirectory)\TestResults
    # continueOnError: true

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunTitle: 'Test run title'
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TEST-*.xml'
      mergeTestResults: true
      # failTaskOnFailedTests: true
      # failTaskOnMissingResultsFile: true
      # buildPlatform: 'BuildPlatform'
      # buildConfiguration: 'BuildConfiguration'
