name: Zipcode Tests
 
variables:
  CI: true
 
trigger: none
  # - main
 
jobs:
  - job: test
    timeoutInMinutes: 60
    pool:
      vmImage: "ubuntu-latest"
 
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "20.x"
          checkLatest: true
        displayName: "Install Node.js"

      - script: |
          npm ci
        displayName: "Install dependencies"
 
      # - script: |
      #     npx playwright install --with-deps
      #   displayName: "Install Playwright Browsers"
 
      - script: |
          npx playwright test -g "Test zipcodes"
        displayName: "Test zipcodes"

      - script: |
          npx playwright test -g "Test zipcodes with parameters"
        env:
          TEST_FILENAME: "usps-zipcodes-MA.csv"
        displayName: "Test zipcodes with parameters"
        condition: always()

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: "**/results.xml"
          testRunTitle: "Playwright Tests"
        displayName: "Publish test results"
        condition: always()
 
      - publish: $(System.DefaultWorkingDirectory)/test-results
        artifact: test-results
        # always create the artifact, this is useful for debugging failed tests
        displayName: "Publish artifacts"
        condition: always()


# -----------------------------------------------------------------------------
# References:
#
# * Automating End-to-End testing with Playwright and Azure Pipelines
#   https://techcommunity.microsoft.com/t5/azure-architecture-blog/automating-end-to-end-testing-with-playwright-and-azure/ba-p/3883704
#
# * Playwright in an Azure DevOps Pipeline
#   https://timdeschryver.dev/blog/playwright-in-an-azure-devops-pipeline
#
# * Include attachments to your Playwright report
#   https://timdeschryver.dev/blog/include-attachments-to-your-playwright-report
#
# * Playwright Reporters: How to Integrate with Azure DevOps Pipelines
#   https://ultimateqa.com/playwright-reporters-how-to-integrate-with-azure-devops-pipelines/
# -----------------------------------------------------------------------------
